backmyitem/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static

from django.contrib.auth.views import LoginView
from django.contrib.auth.views import password_reset, password_reset_done, password_reset_confirm, \
    password_reset_complete
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from . import settings

urlpatterns = [
                  url(r'^admin/', admin.site.urls),
                  url(r'^auth/', include('social_django.urls', namespace='social')),  # <- Here
                  url(r'^', include('feed.urls')),
                  url(r'^login/$', LoginView.as_view(), name="login"),
                  url(r'change-password/',
                      auth_views.PasswordChangeView.as_view(template_name='registration/password_change_form.html'), ),
                  url(r'^password_reset/$', password_reset, name='password_reset_reset1'),
                  url(r'^password_reset/done/$', password_reset_done, name='password_reset_done'),
                  url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
                      password_reset_confirm, name='password_reset_confirm'),
                  url(r'^reset/done/$', password_reset_complete, name='password_reset_complete'),


              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

feed/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth.views import LoginView


app_name = 'feed'
urlpatterns = [
    url(r'^$', views.IndexView, name='index'),
    url(r'^report$', views.ReportCreate.as_view(), name='report'),
    url(r'^detail/(?P<pk>[0-9]+)/$', views.ReportDetail.as_view(), name='detail'),
    url(r'^category/(?P<slug>\w+)/$', views.SearchItemType.as_view(), name='category'),
    url(r'^signup$', views.SignUpForm.as_view(), name='signup'),
    url(r'^login$', views.LoginForm.as_view(), name='login'),

    url(r'^logout$', views.logout_view, name='logout'),
    url(r'^u/(?P<username>\w+)/$', views.Profile, name='profile'),
    url(r'^update/(?P<pk>[0-9]+)/$', views.ReportUpdate.as_view(), name='report-update'),
    url(r'^delete/(?P<pk>[0-9]+)/$', views.ReportDelete.as_view(), name='report-delete'),


    # notification

    url(r'^notification/$', views.mynotification, name='mynotification'),
    url(r'^read_notification/$', views.read_Notification, name='readnotification'),
    url(r'^notification/show/(?P<notification_id>\d+)/$', views.show_notification, name='show_notification'),
    url(r'^notification/read/(?P<notification_id>\d+)/$', views.read_notification, name='read_notification'),
    url(r'^notification/request/(?P<pk>[0-9]+)/$', views.RequestItem.as_view(), name='request'),


    #static pages
    url(r'^about/$', views.home_page, name='about'),
    url(r'^contact/$', views.Contact_page.as_view(), name='contact'),
    url(r'^team/$', views.TeamPage , name='team'),
    url(r'^privacy/$', views.privacy_page, name='privacy'),


]

feed/models.py
from django.core.files.uploadedfile import InMemoryUploadedFile
from django.core.validators import RegexValidator
from django.db import models
from django.utils import timezone
from django.core.urlresolvers import reverse
from django import forms
from django.conf import settings
from django.core.validators import MaxValueValidator
from django.db import models
from django.contrib.auth.models import User
from PIL import Image
from io import BytesIO
import sys


def get_uplaod_file_name(image, filename):
    return u'photos/%s/%s_%s' % (str(image.owner),
                                 str(timezone.now()).replace('.', '_'),
                                 filename)


class Report_item(models.Model):
    owner = models.ForeignKey(settings.AUTH_USER_MODEL)
    title = models.CharField(max_length=255, help_text='*Title for the post e.g. item identity')
    item_type = models.CharField(default="", max_length=100,
                                 help_text='*Enter the item name you found e.g. Marksheet,key,wallet')
    location = models.CharField(max_length=255, help_text='*Enter the address and city where you found this item')
    date = models.DateTimeField(default=timezone.now)
    Description = models.TextField(blank=True, null=True, help_text='*Enter full description about item')
    publish = models.BooleanField(default=False)

    image = models.ImageField(default="add Item image",
                              upload_to=get_uplaod_file_name)

    def save(self):
        im = Image.open(self.image)
        output = BytesIO()
        im = im.resize((500, 500))

        im.save(output, format='PNG', optimize=True, quality=95)
        output.seek(0)

        self.image = InMemoryUploadedFile(output, 'ImageField', "%s.png" % self.image.name.split('.')[0], 'image/jpeg',
                                          sys.getsizeof(output), None)

        super(Report_item, self).save()

    def __str__(self):
        return self.title + "      " + str(self.publish)

    def get_absolute_url(self):
        return reverse('feed:detail', kwargs={'pk': self.pk})

    class Meta:
        ordering = ["-date"]



class UserNotification(models.Model):
    Name = models.CharField(max_length=250)
    Mobile_No = models.CharField(max_length=10, validators=[RegexValidator(r'^\d{1,10}$')])
    Proof = models.TextField()
    viewed = models.BooleanField(default=False)
    user = models.ForeignKey(User)
    date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.Name

    class Meta:
        ordering = ["-date"]


class ContactHelp(models.Model):
    Name = models.CharField(max_length=250)
    Email = models.EmailField(blank=False, null=False)
    query = models.TextField(blank=False, null=False)
    date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.query

# Create your models here.

feed/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Report_item

class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('first_name','username','email','password1','password2')




class LoginForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('email','password1')



class ReportForm(forms.ModelForm):
    class Meta:
        model = Report_item
        fields = ('title', 'item_type', 'location', 'image', 'Description')

feed/views.py
from django.contrib.auth.models import User
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.core.validators import validate_email
from django.forms import Textarea, forms, TextInput, ImageField
from django.shortcuts import render, redirect, render_to_response
from django.http import HttpResponse, HttpResponseRedirect
from django.views.generic.edit import FormMixin
from decouple import config
from .models import Report_item, UserNotification, ContactHelp
from django.views import generic
from django.contrib.auth import login, authenticate
from django.shortcuts import render, redirect
from django.views.generic import View, UpdateView, DeleteView
from .forms import SignUpForm, LoginForm, ReportForm
from django.contrib.auth import logout
from django.contrib.auth import get_user_model
from django.core.urlresolvers import reverse_lazy
from django.db.models import Q
from PIL import Image


def IndexView(request):
    query_list = Report_item.objects.filter(publish=True)
    query = request.GET.get('q')
    if query:
        query_list = query_list.filter(Q(title__icontains=query) |
                                       Q(item_type__icontains=query) |
                                       Q(location__icontains=query) |
                                       Q(Description__icontains=query)).distinct()

    paginator = Paginator(query_list, 5)
    page = request.GET.get('page')
    try:
        qs = paginator.page(page)
    except PageNotAnInteger:
        qs = paginator.page(1)
    except EmptyPage:
        qs = paginator.page(paginator.num_pages)
    title = "Home-Back My Item"
    context = {
        "object_list": qs
    }

    return render(request, "feed/index.html", context)


class SearchItemType(generic.ListView):
    template_name = "feed/index.html"

    def get_queryset(self):
        query_list = Report_item.objects.filter(publish=True)
        slug = self.kwargs.get("slug")
        if slug:
            query_list = query_list.filter(Q(item_type__icontains=slug))
        return query_list


class ReportCreate(generic.CreateView):
    model = Report_item
    fields = ['title', 'item_type', 'location', 'image', 'Description']

    def get_form(self, form_class=None):
        if form_class is None:
            form_class = self.get_form_class()
        form = super(ReportCreate, self).get_form(form_class)
        form.fields['title'].widget = TextInput(
            attrs={'placeholder': '*Enter UID e.g. CBSE Marksheet Roll number 0506***'})
        form.fields['item_type'].widget = TextInput(
            attrs={'placeholder': '*What do you found e.g. marksheet,passport,key,wallet'})
        form.fields['location'].widget = TextInput(
            attrs={'placeholder': '*Enter street and city name where you found this item'})
        form.fields['Description'].widget = Textarea(
            attrs={'rows': 4, 'cols': 15, 'placeholder': 'Optional Field: Any other related detail'})

        return form

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.owner = self.request.user
        self.object.save()
        return FormMixin.form_valid(self, form)


class ReportDetail(generic.DetailView):
    model = Report_item
    template_name = 'feed/detail.html'


class SignUpForm(generic.CreateView):
    form_class = SignUpForm
    template_name = "feed/SignUp.html"

    def get(self, request):
        title = "SignUp - BackMyItem"
        form = self.form_class(None)
        context = {
            "title": title,
            "form": form,
        }
        return render(request, self.template_name, context)

    def post(self, request):

        form = self.form_class(request.POST)
        if form.is_valid():
            print("form valid")
            user = form.save(commit=False)
            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']
            user.set_password(password)
            form.save()
            user = authenticate(username=username, password=password)
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect('feed:index')
        else:
            print(form.errors)

        return render(request, self.template_name, {'form': form})


class LoginForm(generic.CreateView):
    print("login")
    form_class = LoginForm
    template_name = "feed/SignUp.html"

    def get(self, request):
        title = "Login to BackMyItem"
        form = self.form_class(None)
        context = {
            "title": title,
            "form": form,

        }
        return render(request, self.template_name, context)

    def Post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            try:
                print("try")
                username = request.POST['username']
                username = User.objects.get(email=username).username  # Get username with email
                password = request.POST['password']
                validate_email(username)  # If it's a valid email
                user = authenticate(request, username=username, password=password)
                if user is not None:
                    if user.is_active:
                        login(request, user)
                        return redirect('')

            except:
                print("except")
                UserModel = get_user_model()

                password = request.POST['password']
                user = authenticate(request, username=username, password=password)
                if user is not None:
                    if user.is_active:
                        login(request, user)
                        return redirect('')
        else:
            print(form.errors)


def logout_view(request):
    logout(request)
    query_list = Report_item.objects.filter(publish=True)
    return render(request, "feed/index.html", {'object_list': query_list})


def Profile(request, username):
    print(username)
    title = username + " - BackMyItem"
    qs = Report_item.objects.filter(owner__username=username)
    context = {
        "object_list": qs,
        "title": title,
    }
    return render(request, "feed/profile.html", context)


class ReportUpdate(UpdateView):
    model = Report_item
    fields = ['title', 'item_type', 'location', 'image', 'Description']


class ReportDelete(DeleteView):
    model = Report_item
    success_url = reverse_lazy('feed:index')


class RequestItem(generic.CreateView):
    model = UserNotification
    fields = ['Name', 'Mobile_No', 'Proof']

    def get_form(self, form_class=None):
        if form_class is None:
            form_class = self.get_form_class()
        form = super().get_form(form_class)
        form.fields['Name'].widget = TextInput(attrs={'placeholder': '*Enter your name'})
        form.fields['Mobile_No'].widget = TextInput(
            attrs={'placeholder': "*Enter your's mobile number to get a call back from angel"})
        form.fields['Proof'].widget = TextInput(attrs={'placeholder': '*enter proof you have for your lost item'})
        return form

    def form_valid(self, form):
        print(self.kwargs)

        self.object = form.save(commit=False)
        qs = Report_item.objects.filter(id=self.kwargs.get("pk"))
        self.object.user = qs[0].owner
        self.object.save()
        return HttpResponse(
            "<p>Your request has been proceed.</p><br><p>Your will get call from your's angel soon if your's claim to"
            " item is valid.</p><br>"
            "<hr><p>Go back to <a href='https://backmyitem.com'>homepage</a></p>"
            "")


def show_notification(request, notification_id):
    n = UserNotification.objects.get(id=notification_id)
    title = "Requested by " + n.Name
    context = {
        "n": n,
        "title": title,
    }
    n.viewed = True
    n.save()
    return render(request, "feed/notification.html", context)


def read_notification(request, notification_id):
    n = UserNotification.objects.get(id=notification_id)
    n.viewed = True
    n.save()
    return HttpResponse("<h1>Your request has been processed</h1>")


def mynotification(request):
    n = UserNotification.objects.filter(user=request.user, viewed=False)
    print(type(n))
    return render_to_response("feed/loggedin.html",
                              {'full_name': request.user.first_name, 'notification': n, })


def read_Notification(request):
    n = UserNotification.objects.filter(user=request.user)
    context = {
        'full_name': request.user.first_name,
        'notification': n,
        'title': "All Notifications"
    }
    print(type(n))
    return render_to_response("feed/loggedin.html",
                              context)


def home_page(request):
    title = "About BackMyItem"
    return render(request, "static_page/about_us.html", {"title": title})


def privacy_page(request):
    title = "Privacy of BackMyItem"
    return render(request, "static_page/privacy.html", {"title": title})


class Contact_page(generic.CreateView):
    model = ContactHelp
    fields = ['Name', 'Email', 'query']
    success_url = reverse_lazy('feed:index')


def TeamPage(request):
    title = "BackMyItem Team"
    return render(request, "static_page/our_team.html", {"title": title})


def notification_context(request):
    if request.user.is_anonymous:
        return {}
    n = UserNotification.objects.filter(user=request.user, viewed=False)
    return {
        'notification': n,
        'count': n.count(),
    }


def api_context(request):
    key = config('api_key')
    return {
        'api_key': key,
    }

feed/templates/feed/base.html
{% load static %}
<title>
        {% block title %} becomes someone's happiness {% endblock %}
     </title>
{% include "feed/header.html" %}
{% block content%}

{% endblock %}
{% include "feed/footer.html" %}

feed/templates/feed/footer.html
<footer>
<div class="container">
        <div class="row">
            <div class="col-md-4">
                <ul><h4><b>Get to Know Us</b></h4>
                    <li><h5><a href="{% url 'feed:about'%}">About Us</a></h5></li>
                    <li><h5><a href="{% url 'feed:contact'%}">Contact Us</a></h5></li>
                    <li><h5><a href="{% url 'feed:team'%}">Our Team</a></h5></li>
                </ul>
            </div>
            <div class="col-md-4">
                    <ul><h4><b>Follow US</b></h4>
                    <li><h5><a href="https://www.facebook.com/Back-My-Item-267792973827571/?modal=admin_todo_tour"> Facebook</a></h5></li>
                        <li><h5><a href="https://twitter.com/backmyitem">Twitter</a></h5></li>
                    <li><h5>Instagram</h5></li>
                </ul>
            </div>
            <div class="col-md-4">
                <ul><h4><b>Useful Links</b></h4>
                    <li><h5><a href="{% url 'feed:login'%}"> Login</a></h5></li>
                    <li><h5><a href="{% url 'feed:signup'%}"> SignUp</a></h5></li>
                    <li><h5><a href="{% url 'feed:report'%}">Report</a></h5></li>
                    <li><h5><a href="{% url 'feed:logout' %}">Logout</a></h5></li>


                </ul>
            </div>
        </div>
        <div class="row">
            <div class="col-md-3">

            </div>
            <div class="col-md-6">
                <p style="text-align:center">©2019, backmyitem </p>
            </div>
            <div class="col-md-3">

            </div>
        </div>

</div>
</footer>
<br>
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script>
  $( function() {
    var category = [
      "Marksheet",
      "Passport",
      "Key",
      "PAN Card",
      "ATM Card",
      "Documents",
      "Wallet",
      "Purse",
      "Bag",
      "Mobile",
      "Laptop",
      "Pendrive",
      "Electronic Gadgets",
      "others",
    ];
    $( "#id_item_type" ).autocomplete({
      source: category
    });
  } );
  </script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script type="text/javascript">
function googleTranslateElementInit() {
  new google.translate.TranslateElement({pageLanguage: 'en'}, 'google_translate_element');
}
</script>
<script>
    $(".nav a").on("click", function(){
   $(".nav").find(".active").removeClass("active");
   $(this).parent().addClass("active");
});
</script>
<script type="text/javascript" src="//translate.google.com/translate_a/element.js?cb=googleTranslateElementInit">
</script>
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = 'https://connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v3.1&appId=297036774184262&autoLogAppEvents=1';
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));
</script>
<script type="text/javascript">
    function ActivatePlacesSearch(){
        var input=document.getElementById('id_location');
        var autocomplete=new google.maps.places.Autocomplete(input);
    }


</script>

<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key={{ api_key }}&libraries=places&callback=ActivatePlacesSearch">

</script>
<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">

<style>


</style>


<script>
  window.fbAsyncInit = function() {
    FB.init({
      appId      : '{your-app-id}',
      cookie     : true,
      xfbml      : true,
      version    : '{api-version}'
    });

    FB.AppEvents.logPageView();

  };

  (function(d, s, id){
     var js, fjs = d.getElementsByTagName(s)[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement(s); js.id = id;
     js.src = "https://connect.facebook.net/en_US/sdk.js";
     fjs.parentNode.insertBefore(js, fjs);
   }(document, 'script', 'facebook-jssdk'));
</script>
</body>
</html>

feed/templates/feed/form_template.html
{% for field in form %}
<div class="row">
    <div class="signupdiv col-md-5">
        {{field.label_tag}}
    </div>
    <div class="signupfield col-md-7">
        {{ field }}
    </div>
</div>
{% endfor %}

feed/templates/feed/header.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head profile="http://www.w3.org/2005/10/profile">
    <meta charset="UTF-8">
    <link rel="icon" type="image/png" href="{% static 'img/fevicon.png' %}" />

<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-125393309-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-125393309-1');
</script>



    <style>
.fb-share-button{
margin-top:0 auto%;
width:100%!important;
height:100%!important;

}

.share-table{
border-collapse: separate;
            border-spacing: 55px 1px !important;
            border: 0px !important;

}
.request-to-return{

word-spacing: -10px!important;
}

        </style>
    <meta charset="utf-8">
    <link rel="stylesheet" href='{% static "css/base.css" %}'>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

</head>
<body>

<nav class="navbar navbar-default navbar-fixed-top ">
    <div class="container">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'feed:index' %}">FindMyItem</a>

    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <li class=""><a href="{% url 'feed:index' %}"><span class="glyphicon glyphicon-home"></span>&nbsp;&nbsp;Home</a></li>
        <li><a href="{% url 'feed:report' %}"><span class="glyphicon glyphicon-edit"></span>&nbsp;&nbsp;Report</a></li>
      </ul>
          {% if user.is_authenticated %}
        <ul class="nav navbar-nav navbar-left">
        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="true"><span class="glyphicon glyphicon-bullhorn">&nbsp;Notification (<b>{{ count }}</b>)</span></a>

            <ul class="dropdown-menu notify-drop">
            <!-- end notify title -->
            <!-- notify content -->
            <div class="drop-content">
            {% if notification %}
                <table class="notify-table">
                {% for n in notification %}
                    <tr><td><p><a href="{% url 'feed:show_notification' n.id %}"><b>{{n.Name}}</b> requested for the item</a></p></td></tr>
                {% endfor %}
                </table>
                <hr>
                <p><a href="{% url 'feed:readnotification' %}">View All Notification</a></p>
            {% else %}
             <div class="thumbnail-center">
                 <font size="4">
                    <p><a href="{% url 'feed:readnotification' %}">View old Notification</a></p>
                 </font>
             </div>
            {% endif %}
            </div>
          </ul>
        </li>
      </ul>
        {% endif %}
      </ul>
      <ul class="nav navbar-nav navbar-right">
      {% if not user.is_authenticated %}
            <li><a href="{% url 'feed:signup' %}"><span class="glyphicon glyphicon-user"></span>&nbsp;Sign Up</a></li>
            <li><a href="{% url 'login' %}"><span class="glyphicon glyphicon-log-in"></span>&nbsp;Login</a></li>
      {% else %}
          <li><a href="{% url 'feed:profile' user.username %}"><span class="glyphicon glyphicon-user"></span>&nbsp;{{ user.username }}</a></li>
          <li><a href="{% url 'feed:logout' %}"><span class="glyphicon glyphicon-log-out"></span>&nbsp;logout</a></li>
      </ul>
        </li>
        {% endif %}
        </ul>
    </div></div>
        </div>
</nav>
<div class="mobile-main-header">
<div class="mobile-header headerrow">
    <div class="col-md-12 mob-header" style="text-align:center;">
        <a href="{% url 'feed:index' %}">FindMyItem</a>
    </div>
</div>
<table class="table mobile-header-table table-reponsive mob-header-table">
    <tr>
        <td class="mobile-header-td"><a href="{% url 'feed:index' %}"><span class="glyphicon glyphicon-home"></span>&nbsp Home</a></td>
        <td class="mobile-header-td"><a href="{% url 'feed:report' %}"><span class="glyphicon glyphicon-edit"></span>&nbsp;&nbsp;Report</a></td>
        {% if not user.is_authenticated %}
                <td class="mobile-header-td"><span class="glyphicon glyphicon-bullhorn">&nbsp;</span>Notifs</a></td>

        {% else %}
        <td class="mobile-header-td"><a href="{% url 'feed:readnotification' %}"><span class="glyphicon glyphicon-bullhorn">&nbsp;</span>Notifs<small>(<b>{{ count }}</b>)</small></a></td>

         {% endif %}
        {% if not user.is_authenticated %}
        <td class="mobile-header-td"> <a href="{% url 'login' %}"><span class="glyphicon glyphicon-log-in"></span>&nbsp;Login</a></td>
        {% else %}
        <td class="mobile-header-td"><a href="{% url 'feed:profile' user.username %}"><span class="glyphicon glyphicon-user"></span>&nbsp;{{ user.username }}</a></td>
        {% endif %}
    </tr>

</table>

</div>
<br>

feed/templates/feed/login_user.html
<!DOCTYPE html>
<html>
<head>
    <title>Login</title>
</head>
<body>
    <form method="POST" action="{% url 'feed:report' %}">
        {% csrf_token %}
        <p>
            <label>Username</label>
            <input type="text" name="username">
        </p>
        <p>
            <label>Password</label>
            <input type="password" name="password">
        </p>
        <button type="submit">Login</button>
    </form>

</body>
</html>

feed/templates/feed/profile.html
{% extends "feed/base.html" %}
{% block title %} {{ title }} {% endblock %}

{% block content %}
<div class="container">
<div class="row">
      <div class="col-md-6 col-md-push-3">
          <div class="thumbnail-center-profile">
            <font size="2" style="color:black;">
            <p>Hello &nbsp {{ user.first_name }} &nbsp Thanks to make the world a better place</p><br>
                <p>Your's content</p>
            </font>
        </div>

      {% for obj in object_list %}
      <div class="thumbnail"  style="cursor: pointer;">
          <div class="row">
              <div class="col-md-9">
                  <table class="mytable table-responsive">
                      <tr><td class="my-td-item"><h5><b>Title</b></h5></td><td><h5>{{ obj.title }}</h5></td></tr>
                      <tr><td class="my-td-item"><h5><b>Item Type</b></h5></td><td><h5>{{ obj.item_type }}</h5></td></tr>
                      <tr><td class="my-td-item"><h5><b>Location</b></h5></td><td><h5>{{ obj.location }}</h5></td></tr>
                      <tr><td colspan="2" class="post-review"><p><b>{% if obj.publish is False%}Your Post is in review{% endif %}</b></p></td></tr>
                  </table>
              </div>
              <div class="col-md-3">
                  <img class="img-responsive center" src="{{ obj.image.url }}" alt="backmyitem" width="80" height="100" style="margin: 0 auto;">
                  <br><b><p style="font-size: 10px;text-align:center;">Posted Date</b><br>{{ obj.date }}</p>
              </div>
          </div>
          <table class="mytable table-responsive">
              <tr><td class="my-td-item"><a href="{% url 'feed:detail' obj.id %}">
          <span class="glyphicon glyphicon-check"></span> Read_More
        </a></td>
              <td class="my-td-item"><a href="{% url 'feed:report-update' obj.id %}">
          <span class="glyphicon glyphicon-edit"></span> Edit
        </a></td>
              <td class="my-td-item"><a href="{% url 'feed:report-delete' obj.id %}">
          <span class="glyphicon glyphicon-trash"></span> Trash
              </a></td></tr>

          </table>

      </div>
      {% endfor %}

  </div>

  <div class="col-md-3 col-md-pull-6">

  </div>


  <div class="col-md-3">

  </div>
  </div>
</div>
 {% endblock %}

feed/templates/feed/report_item_confirm_delete.html
{% extends 'feed/base.html'%}
{% block title %} {{ title }} {% endblock %}

{% block content %}
<div class="row">
    <div class="col-md-3">
    </div>
    <div class="col-md-6">
        <div class="thumbnail">
            <form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm">
</form>

        </div>
    </div>
    <div class="col-md-3">
    </div>
</div>
{% endblock %}